#Fetching the latest node image on apline
FROM alpine:latest
RUN mkdir -p /frontend
RUN apk add --no-cache nodejs npm

# Setting up the work directory
WORKDIR /frontend

# Installing dependencies
COPY package*.json .

# Copying all the files in our project
COPY . .
RUN npm install
EXPOSE 3000

# Starting our application
CMD npm start

#dfile